In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px
root = pd.read_csv(r"C:\Users\dell\Downloads\ST - SQL ALL PRACTICE FILES\All Excel Practice Files\employee_data.csv")
root

,employee_id,first_name,last_name,email,department,salary,joining_date,age
0,1,Joshua,Ramos,alexandra29@gmail.com,Operations,65313.80,23-05-2024,42
1,2,Christina,Clark,littlekyle@yahoo.com,IT,58827.32,02-10-2021,46
2,3,Jonathon,Sullivan,tannerivan@johnson.com,Operations,57427.31,30-04-2020,50
3,4,Clinton,Aguirre,jamieortega@yahoo.com,HR,45352.74,04-04-2021,55
4,5,Veronica,Weber,trevinosteven@ramos.com,Operations,78772.56,06-10-2020,51
...,...,...,...,...,...,...,...,...
995,996,Brandi,Cowan,qsimmons@gmail.com,Finance,97102.57,07-11-2024,41
996,997,Michael,Gray,curtisruben@gmail.com,IT,40509.73,11-03-2023,37
997,998,Cassandra,Rodriguez,brittneytran@dunlap.info,Finance,72886.03,25-07-2024,32
998,999,April,Howard,crystalcohen@smith.com,Operations,32177.63,06-04-2022,29
999,1000,Benjamin,Palmer,darylsnyder@williams.com,IT,87670.82,03-04-2020,38

In [2]:
root.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   employee_id   1000 non-null   int64
 1   first_name    1000 non-null   object
 2   last_name     1000 non-null   object
 3   email         1000 non-null   object
 4   department    1000 non-null   object
 5   salary        1000 non-null   float64
 6   joining_date  1000 non-null   object
 7   age           1000 non-null   int64
dtypes: float64(1), int64(2), object(5)
memory usage: 62.6+ KB

In [3]:
root["joining_date"] = pd.to_datetime(root["joining_date"], format="%d-%m-%Y")

In [4]:
root.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   employee_id   1000 non-null   int64
 1   first_name    1000 non-null   object
 2   last_name     1000 non-null   object
 3   email         1000 non-null   object
 4   department    1000 non-null   object
 5   salary        1000 non-null   float64
 6   joining_date  1000 non-null   datetime64[ns]
 7   age           1000 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 62.6+ KB

In [5]:
root.describe()

       employee_id       salary         joining_date          age
count  1000.000000   1000.00000                 1000  1000.000000
mean    500.500000  65112.38533  2022-06-07 18:43:12    40.978000
min       1.000000  30102.76000  2019-12-07 00:00:00    22.000000
25%     250.750000  48008.14000  2021-03-20 12:00:00    31.000000
50%     500.500000  64585.64000  2022-06-13 00:00:00    41.000000
75%     750.250000  82785.63000  2023-08-30 00:00:00    51.000000
max    1000.000000  99969.69000  2024-11-27 00:00:00    60.000000
std     288.819436  19925.16810                  NaN    11.398923

In [6]:
root.shape

(1000, 8)

In [7]:
root.columns

Index(['employee_id', 'first_name', 'last_name', 'email', 'department',
       'salary', 'joining_date', 'age'],
      dtype='object')

In [8]:
root.head()

,employee_id,first_name,last_name,email,department,salary,joining_date,age
0,1,Joshua,Ramos,alexandra29@gmail.com,Operations,65313.80,2024-05-23,42
1,2,Christina,Clark,littlekyle@yahoo.com,IT,58827.32,2021-10-02,46
2,3,Jonathon,Sullivan,tannerivan@johnson.com,Operations,57427.31,2020-04-30,50
3,4,Clinton,Aguirre,jamieortega@yahoo.com,HR,45352.74,2021-04-04,55
4,5,Veronica,Weber,trevinosteven@ramos.com,Operations,78772.56,2020-10-06,51

In [9]:
root.isnull().sum()

employee_id     0
first_name      0
last_name       0
email           0
department      0
salary          0
joining_date    0
age             0
dtype: int64

In [10]:
root.sort_index()

,employee_id,first_name,last_name,email,department,salary,joining_date,age
0,1,Joshua,Ramos,alexandra29@gmail.com,Operations,65313.80,2024-05-23,42
1,2,Christina,Clark,littlekyle@yahoo.com,IT,58827.32,2021-10-02,46
2,3,Jonathon,Sullivan,tannerivan@johnson.com,Operations,57427.31,2020-04-30,50
3,4,Clinton,Aguirre,jamieortega@yahoo.com,HR,45352.74,2021-04-04,55
4,5,Veronica,Weber,trevinosteven@ramos.com,Operations,78772.56,2020-10-06,51
...,...,...,...,...,...,...,...,...
995,996,Brandi,Cowan,qsimmons@gmail.com,Finance,97102.57,2024-11-07,41
996,997,Michael,Gray,curtisruben@gmail.com,IT,40509.73,2023-03-11,37
997,998,Cassandra,Rodriguez,brittneytran@dunlap.info,Finance,72886.03,2024-07-25,32
998,999,April,Howard,crystalcohen@smith.com,Operations,32177.63,2022-04-06,29
999,1000,Benjamin,Palmer,darylsnyder@williams.com,IT,87670.82,2020-04-03,38

In [11]:
root.iloc[0:6,0:4]

   employee_id first_name last_name                    email
0            1     Joshua     Ramos    alexandra29@gmail.com
1            2  Christina     Clark     littlekyle@yahoo.com
2            3   Jonathon  Sullivan   tannerivan@johnson.com
3            4    Clinton   Aguirre    jamieortega@yahoo.com
4            5   Veronica     Weber  trevinosteven@ramos.com
5            6      Louis    Rivera       parksamy@gmail.com

In [12]:
root.loc[0:8,"department" : "salary"]

   department    salary
0  Operations  65313.80
1          IT  58827.32
2  Operations  57427.31
3          HR  45352.74
4  Operations  78772.56
5     Finance  30448.72
6   Marketing  88476.72
7   Marketing  49895.55
8     Finance  88878.64

In [13]:
root[["salary","age","department"]].max()

salary          99969.69
age                   60
department    Operations
dtype: object

In [14]:
root[["salary","department","age"]]

       salary  department  age
0    65313.80  Operations   42
1    58827.32          IT   46
2    57427.31  Operations   50
3    45352.74          HR   55
4    78772.56  Operations   51
..        ...         ...  ...
995  97102.57     Finance   41
996  40509.73          IT   37
997  72886.03     Finance   32
998  32177.63  Operations   29
999  87670.82          IT   38

[1000 rows x 3 columns]

In [15]:
root[root["age"]>50].head()

,employee_id,first_name,last_name,email,department,salary,joining_date,age
3,4,Clinton,Aguirre,jamieortega@yahoo.com,HR,45352.74,2021-04-04,55
4,5,Veronica,Weber,trevinosteven@ramos.com,Operations,78772.56,2020-10-06,51
11,12,Hannah,Carrillo,dianeroberts@becker.com,Operations,82047.41,2024-05-13,59
13,14,Victor,Lamb,michellebrown@finley.com,Finance,55038.09,2024-10-29,56
14,15,Tammy,Collins,cherylbanks@gmail.com,HR,39382.83,2021-03-12,52

In [16]:
root[(root["age"]>40) & (root["salary"]>5000)].head()

,employee_id,first_name,last_name,email,department,salary,joining_date,age
0,1,Joshua,Ramos,alexandra29@gmail.com,Operations,65313.80,2024-05-23,42
1,2,Christina,Clark,littlekyle@yahoo.com,IT,58827.32,2021-10-02,46
2,3,Jonathon,Sullivan,tannerivan@johnson.com,Operations,57427.31,2020-04-30,50
3,4,Clinton,Aguirre,jamieortega@yahoo.com,HR,45352.74,2021-04-04,55
4,5,Veronica,Weber,trevinosteven@ramos.com,Operations,78772.56,2020-10-06,51

In [17]:
root.drop_duplicates("department")

,employee_id,first_name,last_name,email,department,salary,joining_date,age
0,1,Joshua,Ramos,alexandra29@gmail.com,Operations,65313.80,2024-05-23,42
1,2,Christina,Clark,littlekyle@yahoo.com,IT,58827.32,2021-10-02,46
3,4,Clinton,Aguirre,jamieortega@yahoo.com,HR,45352.74,2021-04-04,55
5,6,Louis,Rivera,parksamy@gmail.com,Finance,30448.72,2020-05-05,41
6,7,Sabrina,Gonzalez,rwillis@mason-clark.biz,Marketing,88476.72,2020-10-15,48

In [18]:
root.sort_values(["age","salary"],ascending=False)

,employee_id,first_name,last_name,email,department,salary,joining_date,age
955,956,Michelle,Martin,whitakercarmen@yahoo.com,Operations,92597.05,2021-07-16,60
80,81,Frank,Harper,dannymacdonald@gmail.com,Operations,89616.97,2024-11-24,60
613,614,Mackenzie,Chen,brownjohn@lewis.net,IT,78728.97,2020-12-21,60
985,986,Alex,Johnston,anita53@hotmail.com,Finance,78005.06,2023-03-12,60
112,113,Raymond,Roberts,mary93@bailey.biz,Marketing,66642.13,2022-08-20,60
...,...,...,...,...,...,...,...,...
119,120,Mary,Smith,julieharris@hall.biz,IT,44144.75,2020-03-06,22
637,638,Valerie,Arnold,nelsoncameron@hotmail.com,Operations,43962.85,2020-10-12,22
330,331,Michelle,Lamb,bennettwilliam@smith.biz,HR,33319.16,2021-10-08,22
831,832,Melissa,Walker,alexander84@hotmail.com,HR,31631.32,2021-03-11,22
149,150,Alejandro,Carlson,alexanderlawson@anderson.com,Finance,31515.61,2023-06-01,22

In [19]:
root.where(root["department"]=="HR").head(10)

,employee_id,first_name,last_name,email,department,salary,joining_date,age
0,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
3,4.0,Clinton,Aguirre,jamieortega@yahoo.com,HR,45352.74,2021-04-04,55.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
9,10.0,Adam,Sanchez,luisclark@hotmail.com,HR,88331.24,2020-03-23,38.0

In [20]:
root.query("salary>4000 and department=='IT'")

,employee_id,first_name,last_name,email,department,salary,joining_date,age
1,2,Christina,Clark,littlekyle@yahoo.com,IT,58827.32,2021-10-02,46
12,13,Elizabeth,Johnson,ramirezbriana@hotmail.com,IT,83585.45,2023-12-11,27
19,20,Kristina,Rivera,fbrooks@martin-blair.com,IT,85703.19,2022-12-18,59
24,25,Monica,Olson,zparrish@hotmail.com,IT,75404.05,2021-01-02,24
25,26,Eduardo,Smith,rossjared@montes.com,IT,96756.21,2021-03-31,42
...,...,...,...,...,...,...,...,...
981,982,Adam,Lowe,blopez@carpenter.com,IT,93174.12,2024-09-21,27
989,990,Frank,Miller,jennifer07@manning.com,IT,73566.74,2020-11-19,51
990,991,Dillon,Maldonado,jamesjeanette@gmail.com,IT,31881.60,2020-07-17,56
996,997,Michael,Gray,curtisruben@gmail.com,IT,40509.73,2023-03-11,37
999,1000,Benjamin,Palmer,darylsnyder@williams.com,IT,87670.82,2020-04-03,38

In [21]:
root["City"] ="Mumbai"
root

,employee_id,first_name,last_name,email,department,salary,joining_date,age,City
0,1,Joshua,Ramos,alexandra29@gmail.com,Operations,65313.80,2024-05-23,42,Mumbai
1,2,Christina,Clark,littlekyle@yahoo.com,IT,58827.32,2021-10-02,46,Mumbai
2,3,Jonathon,Sullivan,tannerivan@johnson.com,Operations,57427.31,2020-04-30,50,Mumbai
3,4,Clinton,Aguirre,jamieortega@yahoo.com,HR,45352.74,2021-04-04,55,Mumbai
4,5,Veronica,Weber,trevinosteven@ramos.com,Operations,78772.56,2020-10-06,51,Mumbai
...,...,...,...,...,...,...,...,...,...
995,996,Brandi,Cowan,qsimmons@gmail.com,Finance,97102.57,2024-11-07,41,Mumbai
996,997,Michael,Gray,curtisruben@gmail.com,IT,40509.73,2023-03-11,37,Mumbai
997,998,Cassandra,Rodriguez,brittneytran@dunlap.info,Finance,72886.03,2024-07-25,32,Mumbai
998,999,April,Howard,crystalcohen@smith.com,Operations,32177.63,2022-04-06,29,Mumbai
999,1000,Benjamin,Palmer,darylsnyder@williams.com,IT,87670.82,2020-04-03,38,Mumbai

In [22]:
root.drop(columns="City",inplace=True)

In [23]:
root
root.rename(columns={"employee_id" : "EMP_ID"},inplace=True)

In [24]:
root["age"] = root["age"].transform(lambda x: x+2)
root["department"] = root["department"].transform(lambda x:x.upper())
root

,EMP_ID,first_name,last_name,email,department,salary,joining_date,age
0,1,Joshua,Ramos,alexandra29@gmail.com,OPERATIONS,65313.80,2024-05-23,44
1,2,Christina,Clark,littlekyle@yahoo.com,IT,58827.32,2021-10-02,48
2,3,Jonathon,Sullivan,tannerivan@johnson.com,OPERATIONS,57427.31,2020-04-30,52
3,4,Clinton,Aguirre,jamieortega@yahoo.com,HR,45352.74,2021-04-04,57
4,5,Veronica,Weber,trevinosteven@ramos.com,OPERATIONS,78772.56,2020-10-06,53
...,...,...,...,...,...,...,...,...
995,996,Brandi,Cowan,qsimmons@gmail.com,FINANCE,97102.57,2024-11-07,43
996,997,Michael,Gray,curtisruben@gmail.com,IT,40509.73,2023-03-11,39
997,998,Cassandra,Rodriguez,brittneytran@dunlap.info,FINANCE,72886.03,2024-07-25,34
998,999,April,Howard,crystalcohen@smith.com,OPERATIONS,32177.63,2022-04-06,31
999,1000,Benjamin,Palmer,darylsnyder@williams.com,IT,87670.82,2020-04-03,40

In [25]:
root.nunique()

EMP_ID          1000
first_name       363
last_name        483
email           1000
department         5
salary          1000
joining_date     776
age               39
dtype: int64

In [26]:
root["department"].value_counts()

department
FINANCE       208
IT            206
HR            205
OPERATIONS    191
MARKETING     190
Name: count, dtype: int64

In [27]:
# root.where((root["department"]=="HR") & (root["salary"]>400),other="not found").head(20)
root.loc[(root["department"] == "HR") & (root["salary"] > 400)].head(20)

,EMP_ID,first_name,last_name,email,department,salary,joining_date,age
3,4,Clinton,Aguirre,jamieortega@yahoo.com,HR,45352.74,2021-04-04,57
9,10,Adam,Sanchez,luisclark@hotmail.com,HR,88331.24,2020-03-23,40
14,15,Tammy,Collins,cherylbanks@gmail.com,HR,39382.83,2021-03-12,54
27,28,Bradley,Flowers,david06@johnson-simon.com,HR,71647.02,2021-01-20,25
29,30,Christopher,Wilson,nmurray@rivera.biz,HR,85120.78,2021-04-06,30
31,32,Nancy,Ortiz,claytonmcguire@turner-fowler.com,HR,37425.94,2023-04-18,37
39,40,Katie,Gordon,stephaniegill@hotmail.com,HR,77255.03,2021-12-28,39
41,42,James,Vaughn,jessicaperez@hall.com,HR,47270.87,2023-11-18,53
42,43,Jaime,Evans,millerkathleen@fuller.info,HR,31594.03,2020-04-21,57
44,45,Dwayne,Kline,zjenkins@shaffer.com,HR,55993.32,2023-04-17,33
45,46,Jeremiah,Silva,richardsonmichael@hotmail.com,HR,34163.36,2021-12-23,48
51,52,Melissa,Garcia,anthonypeters@yahoo.com,HR,49094.01,2021-06-20,53
53,54,Steven,Robinson,westariana@griffith-shepherd.info,HR,41451.52,2022-12-08,27
58,59,Fred,Nicholson,vthomas@yahoo.com,HR,59827.76,2020-01-29,54
60,61,Michael,Carlson,conniemorris@yahoo.com,HR,37731.53,2020-07-13,38
64,65,Donna,Gibbs,milleralicia@johnson.com,HR,98453.91,2024-09-26,25
71,72,Roberto,Frost,saraferguson@hotmail.com,HR,97048.59,2024-10-17,55
79,80,Aaron,Foster,ramirezdaniel@anderson.com,HR,90474.37,2024-02-09,58
82,83,Regina,Cruz,iclarke@gmail.com,HR,67870.50,2020-07-08,56
86,87,Jacob,Monroe,cjimenez@barber.com,HR,50172.70,2021-07-04,29

In [28]:
for x in root.__iter__():
    print(x)

EMP_ID
first_name
last_name
email
department
salary
joining_date
age

In [29]:
root.nsmallest(2,"salary")

,EMP_ID,first_name,last_name,email,department,salary,joining_date,age
385,386,Ashley,Peterson,yerickson@guerrero.com,IT,30102.76,2022-10-18,51
652,653,Ryan,Smith,matthew82@yahoo.com,OPERATIONS,30118.59,2022-03-20,27

In [30]:
root.nlargest(4,"age")

,EMP_ID,first_name,last_name,email,department,salary,joining_date,age
47,48,Ricardo,Wilson,michaelhawkins@hotmail.com,IT,31024.79,2022-12-27,62
80,81,Frank,Harper,dannymacdonald@gmail.com,OPERATIONS,89616.97,2024-11-24,62
112,113,Raymond,Roberts,mary93@bailey.biz,MARKETING,66642.13,2022-08-20,62
151,152,Sarah,Garner,ericagrant@hotmail.com,HR,32007.84,2019-12-25,62

In [31]:
root.sample(5)

,EMP_ID,first_name,last_name,email,department,salary,joining_date,age
52,53,David,Flynn,riveraangel@hotmail.com,OPERATIONS,35475.54,2023-03-09,57
426,427,Lisa,Diaz,beltranstephen@hotmail.com,IT,87108.54,2023-09-15,24
963,964,Carla,Barker,jbutler@hotmail.com,HR,76766.15,2020-10-20,47
672,673,Jonathan,Fernandez,walkerjames@wise.net,OPERATIONS,68122.58,2020-02-02,38
780,781,William,Miller,holly18@gmail.com,HR,58016.84,2023-03-13,25

In [32]:
root[["age","salary"]].mean()

age          42.97800
salary    65112.38533
dtype: float64

In [33]:
root["salary"].agg(["min","max","count","sum"])

min         30102.76
max         99969.69
count        1000.00
sum      65112385.33
Name: salary, dtype: float64

In [34]:
func = root.agg({
    "salary" : ["min","max","sum"],
    "age" : ["min","max","count"],
    "department" : ["max","min"]
})
func

            salary     age  department
min       30102.76    24.0     FINANCE
max       99969.69    62.0  OPERATIONS
sum    65112385.33     NaN         NaN
count          NaN  1000.0         NaN

In [35]:
tool = root["department"].value_counts()
tool

department
FINANCE       208
IT            206
HR            205
OPERATIONS    191
MARKETING     190
Name: count, dtype: int64

In [36]:
trans_form = root.transform({
    "department" : [lambda x:x.lower()],
    "age" : [lambda x:x+2],
    "email" : [lambda x:x.upper()]
})
trans_form

     department      age                     email
       <lambda> <lambda>                  <lambda>
0    operations       46     ALEXANDRA29@GMAIL.COM
1            it       50      LITTLEKYLE@YAHOO.COM
2    operations       54    TANNERIVAN@JOHNSON.COM
3            hr       59     JAMIEORTEGA@YAHOO.COM
4    operations       55   TREVINOSTEVEN@RAMOS.COM
..          ...      ...                       ...
995     finance       45        QSIMMONS@GMAIL.COM
996          it       41     CURTISRUBEN@GMAIL.COM
997     finance       36  BRITTNEYTRAN@DUNLAP.INFO
998  operations       33    CRYSTALCOHEN@SMITH.COM
999          it       42  DARYLSNYDER@WILLIAMS.COM

[1000 rows x 3 columns]

In [37]:
root["department"].str[:4]
root["department"].str[::]
root["department"] = root["department"].str.replace("IT","Sen")

In [38]:
root["full_name"] =root["first_name"].str.cat(root["last_name"],sep=" ")
root
# drop the first name and last name column
# root.drop(columns=["first_name","last_name"],inplce=True)

,EMP_ID,first_name,last_name,email,department,salary,joining_date,age,full_name
0,1,Joshua,Ramos,alexandra29@gmail.com,OPERATIONS,65313.80,2024-05-23,44,Joshua Ramos
1,2,Christina,Clark,littlekyle@yahoo.com,Sen,58827.32,2021-10-02,48,Christina Clark
2,3,Jonathon,Sullivan,tannerivan@johnson.com,OPERATIONS,57427.31,2020-04-30,52,Jonathon Sullivan
3,4,Clinton,Aguirre,jamieortega@yahoo.com,HR,45352.74,2021-04-04,57,Clinton Aguirre
4,5,Veronica,Weber,trevinosteven@ramos.com,OPERATIONS,78772.56,2020-10-06,53,Veronica Weber
...,...,...,...,...,...,...,...,...,...
995,996,Brandi,Cowan,qsimmons@gmail.com,FINANCE,97102.57,2024-11-07,43,Brandi Cowan
996,997,Michael,Gray,curtisruben@gmail.com,Sen,40509.73,2023-03-11,39,Michael Gray
997,998,Cassandra,Rodriguez,brittneytran@dunlap.info,FINANCE,72886.03,2024-07-25,34,Cassandra Rodriguez
998,999,April,Howard,crystalcohen@smith.com,OPERATIONS,32177.63,2022-04-06,31,April Howard
999,1000,Benjamin,Palmer,darylsnyder@williams.com,Sen,87670.82,2020-04-03,40,Benjamin Palmer

In [39]:
root[["full_name","age","salary"]].head().style.highlight_max(color="blue")

In [40]:
root[["department","salary"]].head().style.highlight_min(color="green")

In [49]:
high = pd.DataFrame({
    "name" : ["Rohil Thakur","Mohit Sharma","Anmol Mehta ","Nitan Vats","Rajeev Yadav"],
    "Id" : [1,2,3,4,5]
})


low = pd.DataFrame({
    "City" : ["Sonpat","Delhi","Pune","Ncr","Gurugram"],
    "Id" : [1,2,3,4,9]
})

In [ ]:
inner = pd.merge(high,low,on="Id")
(inner)

In [ ]:
left = pd.merge(high,low,on="Id",how="left")
left

In [ ]:
right = pd.merge(high,low,on="Id",how="right")
right

In [ ]:
outer = pd.merge(high,low,on="Id",how="outer")
outer

In [ ]:
join = pd.merge(high,low,left_on="Id",right_on="Id")
join

In [ ]:
cross = pd.merge(high,low,how="cross")
cross

In [ ]:
vertical = pd.concat([high,high])
vertical

In [ ]:
horizontal = pd.concat([high,high],axis=1)
horizontal

In [50]:
fig = px.histogram(root, x="salary", nbins=20,
                   title="Salary Distribution",color="department",template="plotly_dark")
fig.show()

In [51]:
dept_count = root["department"].value_counts().reset_index()
dept_count.columns = ["department", "Count"]
dept_count

   department  Count
0     FINANCE    208
1         Sen    206
2          HR    205
3  OPERATIONS    191
4   MARKETING    190

In [52]:
dept_count12 = root["department"].value_counts().reset_index()
dept_count.columns = ["department", "Count"]
dept_count12
fig = px.bar(dept_count, x="department", y="Count",
             color="department", title="Employees by Department")
fig.show()

In [53]:
root["joining_date"] = pd.to_datetime(root["joining_date"], dayfirst=True)
px.line(root.groupby(root["joining_date"].dt.year).size().reset_index(name="count"),
        x="joining_date", y="count", title="Employees Joined per Year")

In [54]:
px.treemap(root, path=["department"], values="salary",
           title="Total Salary Allocation by Department",color="salary",template="plotly_dark")

In [55]:
px.violin(root, x="department", y="age", box=True, points="all",
          title="Age Distribution by Department",template="plotly_white")

In [56]:
top10 = root.nlargest(10, "salary")
px.bar(top10, x="first_name", y="salary", color="department",
       title="Top 10 Highest Paid Employees",template="plotly_dark")

In [57]:
px.pie(root, names="department", title="Employee Distribution by Department",template="plotly_dark")